project_id = "okntvbjbpdtyhctgiarp"

[functions.ai-reflection]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.request-account-deletion]
verify_jwt = false

[functions.confirm-account-deletion]
verify_jwt = false
